---
repos:
  - repo: https://github.com/michael-elementor/Jenkinslint
    rev: v0.1.1
    hooks:
      - id: validate
  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint
